import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('../components/ChatWindow.svelte', import.meta.url), 'utf8');

assert.match(source, /class="[^"]*chat-console/);
assert.match(source, /class="[^"]*chat-workbench/);
assert.match(source, /class="[^"]*chat-sidebar/);
assert.match(source, /class="[^"]*chat-session-list/);
assert.match(source, /class="[^"]*chat-main/);
assert.match(source, /class="[^"]*chat-toolbar/);
assert.match(source, /messages\.length === 0/);
assert.match(source, /class="[^"]*chat-prompt-grid/);
assert.match(source, /class="[^"]*chat-prompt-chip/);
assert.match(source, /class="[^"]*chat-composer/);
assert.match(source, /class="[^"]*chat-composer-shell/);
assert.match(source, /class="[^"]*chat-composer-input/);
assert.match(source, /class="[^"]*chat-composer-action/);
assert.match(source, /<textarea[^>]*class="[^"]*chat-composer-input/);
assert.match(source, /class="[^"]*select-shell/);
assert.match(source, /class="[^"]*select-icon/);
assert.match(source, /activeContext/);
assert.match(source, /attachment/);
assert.match(source, /class="[^"]*chat-context-status/);
assert.match(source, /Attachment:/);
assert.match(source, /deriveChatViewState/);
assert.match(source, /deriveInitialTab/);
assert.match(source, /deriveChatInteractionState/);
assert.match(source, /deriveTargetChange/);
assert.match(source, /function switchTab/);
assert.doesNotMatch(source, /let activeTab = \$state<'agents' \| 'runtimes'>\('agents'\)/);
assert.doesNotMatch(source, /const availableTabs = chatTabs\.split\(','\)\.filter\(Boolean\)/);
const sendMessageIndex = source.indexOf('async function sendMessage()');
const loadErrorResetIndex = source.indexOf("loadError = '';", sendMessageIndex);
const threadAdoptionIndex = source.indexOf('selectedThread = payload.thread_id', sendMessageIndex);
const runtimesGuardIndex = source.indexOf("activeTab === 'runtimes'", sendMessageIndex);
const sendingGuardIndex = source.indexOf('if (sending) return;', sendMessageIndex);
const sendTargetIndex = source.indexOf('const sendTarget = selectedAgent;', sendMessageIndex);
assert.ok(sendMessageIndex >= 0, 'sendMessage should exist');
assert.ok(threadAdoptionIndex > sendMessageIndex, 'sendMessage should adopt payload.thread_id');
assert.ok(threadAdoptionIndex < loadErrorResetIndex, 'thread adoption should happen in the successful send path');
assert.ok(runtimesGuardIndex > sendMessageIndex, 'sendMessage should guard the runtimes tab');
assert.ok(sendingGuardIndex > sendMessageIndex, 'sendMessage should guard concurrent sends');
assert.ok(sendTargetIndex > sendMessageIndex, 'sendMessage should capture the effective send target');
assert.match(source, /const currentSelection = tab === 'agents' \? selectedAgentTarget : selectedRuntimeTarget;/);
assert.match(source, /deriveTabSelection\(tab, catalog, currentSelection\)/);
assert.match(source, /selectedAgentTarget/);
assert.match(source, /selectedRuntimeTarget/);
assert.match(source, /catalog\.agents\.includes\(sendTarget\)/);
assert.match(source, /if \(!interactionState\.canCreateSession\) return;/);
assert.match(source, /deriveChatInteractionState\(activeTab, sending, selectedAgent, catalog, draft, Boolean\(sessionsEndpoint\)\)/);
assert.match(source, /disabled=\{interactionState\.composerDisabled\}/);
assert.match(source, /disabled=\{!interactionState\.canSend\}/);
assert.match(source, /disabled=\{!interactionState\.canCreateSession\}/);
assert.match(source, /activeTab === 'runtimes' \? 'Runtime planning only/);
assert.match(source, /onchange=\{handleTargetChange\}/);

const promptGridIndex = source.indexOf('class="chat-prompt-grid"');
const emptyStateIndex = source.indexOf('class="chat-empty-state"');
assert.ok(promptGridIndex > emptyStateIndex, 'starter prompts should live inside the empty state block');
